### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by 89gnahT** [radianttap/Spotifier#1]
Hi, I follow the instruction from the Readme to start figuring out the Coordinator pattern of this app. I couldn't run the project since in file SpotifyEndpoint.swift at line 60
`var httpMethod: NetworkHTTPMethod { }`
Xcode send me the error:
 Use of undeclared type 'NetworkHTTPMethod'
Is there anything I need to update in this project or in Avenue to resolve this issue ?

**Comment by radianttap** [comment]
Sounds like regression issue from possible updates in Avenue. I’ll look into this, hopefuliy mater today

**Comment by radianttap** [comment]
Did a quick update for it to compile. Might need update in the `Endpoint.allowEmptyResponseData` for specific endpoints on Spotify.
